/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingsRouteImport } from './routes/writings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ObjectifsRouteImport } from './routes/objectifs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsIndexRouteImport } from './routes/projets/index'
import { Route as ProjetsProjectIdRouteImport } from './routes/projets/$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectifsRoute = ObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsIndexRoute = ProjetsIndexRouteImport.update({
  id: '/projets/',
  path: '/projets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsProjectIdRoute = ProjetsProjectIdRouteImport.update({
  id: '/projets/$projectId',
  path: '/projets/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/objectifs': typeof ObjectifsRoute
  '/stats': typeof StatsRoute
  '/writings': typeof WritingsRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/projets/': typeof ProjetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/objectifs': typeof ObjectifsRoute
  '/stats': typeof StatsRoute
  '/writings': typeof WritingsRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/projets': typeof ProjetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/objectifs': typeof ObjectifsRoute
  '/stats': typeof StatsRoute
  '/writings': typeof WritingsRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/projets/': typeof ProjetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/objectifs'
    | '/stats'
    | '/writings'
    | '/projets/$projectId'
    | '/projets/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/objectifs'
    | '/stats'
    | '/writings'
    | '/projets/$projectId'
    | '/projets'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/objectifs'
    | '/stats'
    | '/writings'
    | '/projets/$projectId'
    | '/projets/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObjectifsRoute: typeof ObjectifsRoute
  StatsRoute: typeof StatsRoute
  WritingsRoute: typeof WritingsRoute
  ProjetsProjectIdRoute: typeof ProjetsProjectIdRoute
  ProjetsIndexRoute: typeof ProjetsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectifs': {
      id: '/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof ObjectifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/': {
      id: '/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof ProjetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$projectId': {
      id: '/projets/$projectId'
      path: '/projets/$projectId'
      fullPath: '/projets/$projectId'
      preLoaderRoute: typeof ProjetsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObjectifsRoute: ObjectifsRoute,
  StatsRoute: StatsRoute,
  WritingsRoute: WritingsRoute,
  ProjetsProjectIdRoute: ProjetsProjectIdRoute,
  ProjetsIndexRoute: ProjetsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
