/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingsRouteImport } from './routes/writings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as ObjectifsRouteImport } from './routes/objectifs'
import { Route as IndexRouteImport } from './routes/index'

const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectifsRoute = ObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/objectifs': typeof ObjectifsRoute
  '/projets': typeof ProjetsRoute
  '/stats': typeof StatsRoute
  '/writings': typeof WritingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/objectifs': typeof ObjectifsRoute
  '/projets': typeof ProjetsRoute
  '/stats': typeof StatsRoute
  '/writings': typeof WritingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/objectifs': typeof ObjectifsRoute
  '/projets': typeof ProjetsRoute
  '/stats': typeof StatsRoute
  '/writings': typeof WritingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/objectifs' | '/projets' | '/stats' | '/writings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/objectifs' | '/projets' | '/stats' | '/writings'
  id: '__root__' | '/' | '/objectifs' | '/projets' | '/stats' | '/writings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObjectifsRoute: typeof ObjectifsRoute
  ProjetsRoute: typeof ProjetsRoute
  StatsRoute: typeof StatsRoute
  WritingsRoute: typeof WritingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectifs': {
      id: '/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof ObjectifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObjectifsRoute: ObjectifsRoute,
  ProjetsRoute: ProjetsRoute,
  StatsRoute: StatsRoute,
  WritingsRoute: WritingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
